name: Publish New Release To PyPI

on:
  release:
    types:
      # This used to be `published` but `released` makes sure not to run when a
      # `prerelease` version has been created.
      # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
      - released

jobs:
  upload-to-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Build and publish
        run: |
          pip install poetry
          poetry install
          poetry build
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish

